### ISSUE TITLE
Publish the new version on npm

### ISSUE THREAD

**Issue by A-312** [mike-marcacci/objectpath#17]
Hi @mike-marcacci,

When do you go to publish the new version ?

Thanks :)

**Comment by mike-marcacci** [comment]
Just published! Do let me know if you have any issues 👍 Thanks again for the contributions!

**Comment by A-312** [comment]
Your package will be used by [node-convict v6](https://github.com/mozilla/node-convict) and some of my personal package that I work on. If I got or see anything I will let you know by making an issue. :)
