### ISSUE TITLE
Problem with Angular Schema Form

### ISSUE THREAD

**Issue by timur-biboev** [mike-marcacci/objectpath#8]
When Angular Schema Form uses ObjectPath, it does not work properly in my case. In schema-form.js (or schemaForm.js):

`// When building with browserify ObjectPath is available as "objectpath" but othwerwise`
`// it's called "ObjectPath".`
`var ObjectPath = window.ObjectPath || objectpath;`

`var sfPath = {parse: ObjectPath.parse};`

But this does not work, because of (in ObjectPath.js):

`if (typeof define === 'function' && define.amd) {`
`	define(function() {`
`		return {ObjectPath: ObjectPath};`
`	});`
`}`

It works if I change like that:
`var ObjectPath = window.ObjectPath || objectpath.ObjectPath;`
or like that:
`var sfPath = {parse: objectpath.ObjectPath.parse};`
or like that:
`		return ObjectPath;`
Is it me doing something wrong? I'm using requirejs, if it does matter.

**Comment by mike-marcacci** [comment]
Hi @timur-biboev - I just made a change that might help here (I don't use AMD in any of my projects). Check out the master branch directly and let me know if it solves your problems.

**Comment by timur-biboev** [comment]
Hi, @mike-marcacci. It seems to solved my problem, thanks.
