### ISSUE TITLE
Array keys are quoted

### ISSUE THREAD

**Issue by Lorless** [mike-marcacci/objectpath#9]
Hi,

just a quick question. Was this ever designed to handle array keys? As it seems to put quotes around everything. So my keys end end going from ['object']['path']['array'][0] to  ['object']['path']['array']['0'] which doesnt work.

**Comment by mike-marcacci** [comment]
Hi @Lorless,

This should definitely work with arrays. What you describe is correct – that it renders each path section as a string – but that's totally OK in javascript! In fact, javascript arrays are really just objects with normal string keys:

```js
console.log(typeof []);
// => object
```

They just take advantage of the fact that in javascript `1..toString() === "1"`, which means that when you use a number to access an "index" you're really just using its string representation to access the corresponding key! Try this out:

```js
var arr = ['a','b'];

console.log(arr[1]);
// => b

console.log(arr['1']);
// => b
```

You can see that accessing the index by either number or string work the same. If you continue to have issues, please reopen, but things should continue to work this way.

**Comment by Lorless** [comment]
@mike-marcacci I did wonder, turned out it was something else causing the problem but I never knew about javascript using keys like that. Thanks!
